version: '3'

services:
  server:
    build: '.'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo:4.4.6'
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/usr/local/var/mongodb